Adjust code for cluster upgrade with more recent numpy
Previously, the code ran fine, but through errors when ran after the
system upgrade in PY3.11 (compared to previous 3.7):

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 3 dimensions. The detected shape was (100, 1, 2) + inhomogeneous part.

In [71]: %debug
> /home/adina/env/memento/lib/python3.11/site-packages/mne/decoding/base.py(476)cross_val_multiscore()
    474         for ii, (train, test) in enumerate(cv_iter)
    475     )
--> 476     return np.array(scores)[:, 0, ...]  # flatten over joblib output.
    477
    478

ipdb> p scores
[[(0.6666666666666666, array([[-2.66771369, -1.25310169, -0.89962676,  2.30116471,  1.15695695,
         0.76301115]]))], [(0.5, array([[-2.72169387, -1.32087398, -1.01370577,  2.29454536,  1.12657167,
         0.65663389]]))], [(0.8333333333333334, array([[-2.67082967, -1.32521605, -0.94481966,  2.24821059,  1.16671281,
         0.71301546]]))], [(1.0, array([[-2.63807248, -1.30806852, -0.93685773,  2.23642356,  1.15784871,
         0.70884523]]))], [(0.6666666666666666, array([[-2.70038559, -1.36870031, -0.95668999,  2.26752926,  1.14931822, [....]